# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c7458c12a590f00ceda336a9193d3e147ab8ffce84950cc224fa2930e5494e32ca7f44a5de6d4468a2ca8d6af2a20ae91425c61b605b89fbeca6fb0a9b69d05

test:
  secret_key_base: ba58ea10a05f641b9a575b1a1d9ccb14e69e7bf8ee06e726fc7cec10bc0aee58ab8bc2321081c026db152f04522c1bed340612fdcde08588e5bb3a41700e8170

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
